version: '3'
services:
  sdaas:
    image: copernicani/data-budget-sdaas
    #ports:
    #  - "29321:8080"
  api:
    image: linkeddatacenter/lodmap2d-api
    ports:
      - "29322:80"
    environment:
      - LODMAP2D_BACKEND=http://sdaas:8080/sdaas/sparql
  webapp:
    image: copernicani/web-budget
    ports:
      - "29323:80"
    environment:
      - LODMAP2D_DATA=http://localhost:29322/
      - LODMAP2D_TITLE=Legge di Bilancio Italiana
      - LODMAP2D_LANG=it
      - LODMAP2D_DESCRIPTION=Visualizzazione interattiva della Legge di Bilancio Italiana
      - LODMAP2D_MATOMO_ID=2
      
