version: '3'
services:
  webapp:
    environment:
      - G0V_API_ENDPOINT=https://data.budget.g0v.it/ldp
      - G0V_STRING_URL=/strings/mef.json
      - G0V_SHOW_MEF_LOGO=0
    build: .
    ports:
      - "29323:8080"